# Propiedades generales del proyecto
sonar.projectKey=APP_Alumno
sonar.projectName='APP_Alumno'
sonar.projectVersion=1.0

# Dirección de tu servidor SonarQube
sonar.host.url=http://localhost:9000

sonar.token=sqp_22f89d41b7af554ead22256926ca8d9e1588ca78

# Directorio base del proyecto (asegurate que apunte al directorio raíz de tu proyecto)
sonar.projectBaseDir=C:/Users/Marina_Chavez/Desktop/Ejemplo_NET/EjemploEntityFramework

# Directorio de las fuentes del proyecto (esto debería apuntar a tu código fuente)
sonar.sources=.

# Directorio donde se encuentran las pruebas unitarias
sonar.tests=C:/Users/Marina_Chavez/Desktop/Ejemplo_NET/EjemploEntityFramework/APP_Alumno.Tests

# Exclusiones (para no incluir archivos que no son relevantes)
sonar.exclusions=**/*.json,**/*.md

# Comando utilizado instalando .scannerwork
# sonar-scanner.bat -D"sonar.projectKey=APP_Alumno" -D"sonar.sources=." -D"sonar.token=sqp_22f89d41b7af554ead22256926ca8d9e1588ca78" -Dsonar.login=admin -Dsonar.password=Octubre2023.