// <auto-generated />
using System;
using APP_Alumno.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APP_Alumno.Migrations
{
    [DbContext(typeof(AlumnoBdContext))]
    partial class AlumnoBdContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("APP_Alumno.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("apellido");

                    b.Property<int?>("CarreraId")
                        .HasColumnType("int")
                        .HasColumnName("carrera_id");

                    b.Property<int?>("Edad")
                        .HasColumnType("int")
                        .HasColumnName("edad");

                    b.Property<DateOnly>("FechaNac")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nac");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CarreraId" }, "fk_alumno_carrera");

                    b.ToTable("alumno", (string)null);
                });

            modelBuilder.Entity("APP_Alumno.Models.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("carrera", (string)null);
                });

            modelBuilder.Entity("APP_Alumno.Models.Alumno", b =>
                {
                    b.HasOne("APP_Alumno.Models.Carrera", "CarreraNavigation")
                        .WithMany("Alumnos")
                        .HasForeignKey("CarreraId")
                        .HasConstraintName("fk_alumno_carrera");

                    b.Navigation("CarreraNavigation");
                });

            modelBuilder.Entity("APP_Alumno.Models.Carrera", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
